language: java
jdk: openjdk8
install: true

cache:
  directories:
    - $HOME/.m2

script:
  - cd backend && mvn -B verify && cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - egnaf@yahoo.com
    on_success: never
    on_failure: always
