server:
  port: 8080
  servlet:
    context-path: /api/0.1

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: false
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
